/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIS;

import Controlador.AccesoSistema;
import java.awt.Color;
import java.awt.MouseInfo;
import java.awt.Point;
import Controlador.*;
public class MenuSistema extends javax.swing.JFrame {

   int x,y ;Controlador basectr=new Controlador();
    public MenuSistema() {
        initComponents();   this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
     LABELFECHA.setText(basectr.DevolverDatosSql("SELECT  FORMAT(CONVERT(DATE,GETDATE()),'d/M/yyyy');", 1));
     labeldni.setVisible(false);
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LABELFECHA = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LABELUSUARIO = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PERFIL = new javax.swing.JLabel();
        labeldni = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemnuevousuarios = new javax.swing.JMenuItem();
        itemtipoproductos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemproductos = new javax.swing.JMenuItem();
        itemclientes = new javax.swing.JMenuItem();
        itemempleados = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        itemconsultausuarios = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        itemtrabajadores = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        Reportes = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        procesos = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 0, true));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FECHA  :  ");

        LABELFECHA.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        LABELFECHA.setForeground(new java.awt.Color(0, 255, 153));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO CONECTADO  : ");

        LABELUSUARIO.setFont(new java.awt.Font("Arial Black", 0, 22)); // NOI18N
        LABELUSUARIO.setForeground(new java.awt.Color(0, 255, 153));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PERFÍL :  ");

        PERFIL.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        PERFIL.setForeground(new java.awt.Color(0, 255, 153));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELFECHA, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LABELUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PERFIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
            .addComponent(LABELFECHA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LABELUSUARIO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PERFIL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(labeldni, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labeldni, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(labeldni, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.png"))); // NOI18N
        jMenu1.setText("Mantenimientos");
        jMenu1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        itemnuevousuarios.setText("Nuevo Usuario");
        itemnuevousuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevousuariosActionPerformed(evt);
            }
        });
        jMenu1.add(itemnuevousuarios);

        itemtipoproductos.setText("Tipo Producto");
        itemtipoproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtipoproductosActionPerformed(evt);
            }
        });
        jMenu1.add(itemtipoproductos);
        jMenu1.add(jSeparator1);

        itemproductos.setText("Productos");
        itemproductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemproductosActionPerformed(evt);
            }
        });
        jMenu1.add(itemproductos);

        itemclientes.setText("Clientes");
        itemclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemclientesActionPerformed(evt);
            }
        });
        jMenu1.add(itemclientes);

        itemempleados.setText("Trabajadores");
        itemempleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemempleadosActionPerformed(evt);
            }
        });
        jMenu1.add(itemempleados);

        jMenuItem1.setText("Cerrar Seción");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem15.setText("Salir del Sistema");
        jMenu1.add(jMenuItem15);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/base.png"))); // NOI18N
        jMenu2.setText("Consultas");
        jMenu2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        itemconsultausuarios.setText("Usuarios");
        itemconsultausuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemconsultausuariosActionPerformed(evt);
            }
        });
        jMenu2.add(itemconsultausuarios);

        jMenuItem7.setText("Productos");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Clientes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        itemtrabajadores.setText("Trabajadores");
        itemtrabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemtrabajadoresActionPerformed(evt);
            }
        });
        jMenu2.add(itemtrabajadores);

        jMenuItem2.setText("Categorias");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/reporte3.png"))); // NOI18N
        Reportes.setText("Reportes");
        Reportes.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jMenuItem12.setText("Ventas");
        Reportes.add(jMenuItem12);

        jMenuItem13.setText("Trabajadores");
        Reportes.add(jMenuItem13);

        jMenuItem14.setText("Clientes");
        Reportes.add(jMenuItem14);

        jMenuBar1.add(Reportes);

        procesos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/venta medic.png"))); // NOI18N
        procesos.setText("Proceso");
        procesos.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        jMenuItem10.setText("Ventas ");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        procesos.add(jMenuItem10);

        jMenuItem11.setText("Compras");
        procesos.add(jMenuItem11);

        jMenuBar1.add(procesos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
      x=evt.getX();y=evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
    Point p = MouseInfo.getPointerInfo().getLocation();
        this.setLocation(p.x - x, p.y - y);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void itemnuevousuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevousuariosActionPerformed
        NewUser nuevouser=new NewUser(this, rootPaneCheckingEnabled);nuevouser.setVisible(true);
    }//GEN-LAST:event_itemnuevousuariosActionPerformed

    private void itemconsultausuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemconsultausuariosActionPerformed
     Usuarios usua=new Usuarios(this, rootPaneCheckingEnabled);usua.setVisible(true);
    }//GEN-LAST:event_itemconsultausuariosActionPerformed

    private void itemtipoproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtipoproductosActionPerformed
       Categorias cate=new Categorias(this, rootPaneCheckingEnabled);cate.setVisible(true);
    }//GEN-LAST:event_itemtipoproductosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
   dispose(); Logín log=new Logín();log.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void itemproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemproductosActionPerformed
      Productos produc=new Productos(this, rootPaneCheckingEnabled);produc.setVisible(true);
    }//GEN-LAST:event_itemproductosActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       categoriaconsulta ctc=new categoriaconsulta(this, rootPaneCheckingEnabled);ctc.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        ConsultaProductos cp=new ConsultaProductos(this, rootPaneCheckingEnabled);cp.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void itemempleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemempleadosActionPerformed
      Empleados emp=new Empleados(this, rootPaneCheckingEnabled);
      emp.setVisible(true);
    }//GEN-LAST:event_itemempleadosActionPerformed

    private void itemclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemclientesActionPerformed
    Clientes cl=new Clientes(this, rootPaneCheckingEnabled);cl.setVisible(true);
    }//GEN-LAST:event_itemclientesActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
       Ventas v=new Ventas(this, rootPaneCheckingEnabled);v.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void itemtrabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemtrabajadoresActionPerformed
      ConsultaEmpleados ce=new ConsultaEmpleados(this, rootPaneCheckingEnabled);
      ce.setVisible(true);
    }//GEN-LAST:event_itemtrabajadoresActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
      ConsultaClientes cl=new ConsultaClientes(this, rootPaneCheckingEnabled);cl.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuSistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LABELFECHA;
    public static javax.swing.JLabel LABELUSUARIO;
    public static javax.swing.JLabel PERFIL;
    public static javax.swing.JMenu Reportes;
    public static javax.swing.JMenuItem itemclientes;
    public static javax.swing.JMenuItem itemconsultausuarios;
    public static javax.swing.JMenuItem itemempleados;
    public static javax.swing.JMenuItem itemnuevousuarios;
    public static javax.swing.JMenuItem itemproductos;
    public static javax.swing.JMenuItem itemtipoproductos;
    public static javax.swing.JMenuItem itemtrabajadores;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public static javax.swing.JLabel labeldni;
    public static javax.swing.JMenu procesos;
    // End of variables declaration//GEN-END:variables
}
